# IF you are any question or bug pls report at tyg165 on discord or on the github page :
#https://github.com/Serialmielpops/Greg-s-TeamSMP-Crack-Version

name: GregsTeamSMP
author: Chifou , alternative version for crack by serial
version: '${version}'
main: fr.gregwl.gregsteamsmp.GregsTeamSMP
api-version: '1.21'
commands:
  team:
    description: main command from the plugin for no-op actions

# Thank you chifou!